- name: Install Go Language on Windows
  hosts: windows
  tasks:
    - name: Download Go Installer
      win_get_url:
        url: https://go.dev/dl/go1.22.3.windows-amd64.msi
        dest: C:\Users\{{ ansible_user}}\Downloads\go.msi

    - name: Install Go using MSI
      win_package:
        path: C:\Users\{{ ansible_user }}\Downloads\go.msi
        state: present
        name: GOPATH
        value: C:\Users\{{ ansible_user  }}\go

    - name: Add Go to System PATH
      win_path: 
        elements: 
          - C:\Program Files\Go\bin
